/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ua.timetracker.desktoptracker.api.admin.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import ua.timetracker.desktoptracker.api.admin.model.TimeLogDtoDurationUnits;

/**
 * TimeLogDtoDuration
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-04-04T22:51:09.521+03:00[Europe/Kiev]")
public class TimeLogDtoDuration {
  public static final String SERIALIZED_NAME_SECONDS = "seconds";
  @SerializedName(SERIALIZED_NAME_SECONDS)
  private Long seconds;

  public static final String SERIALIZED_NAME_ZERO = "zero";
  @SerializedName(SERIALIZED_NAME_ZERO)
  private Boolean zero;

  public static final String SERIALIZED_NAME_NEGATIVE = "negative";
  @SerializedName(SERIALIZED_NAME_NEGATIVE)
  private Boolean negative;

  public static final String SERIALIZED_NAME_NANO = "nano";
  @SerializedName(SERIALIZED_NAME_NANO)
  private Integer nano;

  public static final String SERIALIZED_NAME_UNITS = "units";
  @SerializedName(SERIALIZED_NAME_UNITS)
  private List<TimeLogDtoDurationUnits> units = null;


  public TimeLogDtoDuration seconds(Long seconds) {
    
    this.seconds = seconds;
    return this;
  }

   /**
   * Get seconds
   * @return seconds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getSeconds() {
    return seconds;
  }


  public void setSeconds(Long seconds) {
    this.seconds = seconds;
  }


  public TimeLogDtoDuration zero(Boolean zero) {
    
    this.zero = zero;
    return this;
  }

   /**
   * Get zero
   * @return zero
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getZero() {
    return zero;
  }


  public void setZero(Boolean zero) {
    this.zero = zero;
  }


  public TimeLogDtoDuration negative(Boolean negative) {
    
    this.negative = negative;
    return this;
  }

   /**
   * Get negative
   * @return negative
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getNegative() {
    return negative;
  }


  public void setNegative(Boolean negative) {
    this.negative = negative;
  }


  public TimeLogDtoDuration nano(Integer nano) {
    
    this.nano = nano;
    return this;
  }

   /**
   * Get nano
   * @return nano
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getNano() {
    return nano;
  }


  public void setNano(Integer nano) {
    this.nano = nano;
  }


  public TimeLogDtoDuration units(List<TimeLogDtoDurationUnits> units) {
    
    this.units = units;
    return this;
  }

  public TimeLogDtoDuration addUnitsItem(TimeLogDtoDurationUnits unitsItem) {
    if (this.units == null) {
      this.units = new ArrayList<>();
    }
    this.units.add(unitsItem);
    return this;
  }

   /**
   * Get units
   * @return units
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<TimeLogDtoDurationUnits> getUnits() {
    return units;
  }


  public void setUnits(List<TimeLogDtoDurationUnits> units) {
    this.units = units;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeLogDtoDuration timeLogDtoDuration = (TimeLogDtoDuration) o;
    return Objects.equals(this.seconds, timeLogDtoDuration.seconds) &&
        Objects.equals(this.zero, timeLogDtoDuration.zero) &&
        Objects.equals(this.negative, timeLogDtoDuration.negative) &&
        Objects.equals(this.nano, timeLogDtoDuration.nano) &&
        Objects.equals(this.units, timeLogDtoDuration.units);
  }

  @Override
  public int hashCode() {
    return Objects.hash(seconds, zero, negative, nano, units);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeLogDtoDuration {\n");
    sb.append("    seconds: ").append(toIndentedString(seconds)).append("\n");
    sb.append("    zero: ").append(toIndentedString(zero)).append("\n");
    sb.append("    negative: ").append(toIndentedString(negative)).append("\n");
    sb.append("    nano: ").append(toIndentedString(nano)).append("\n");
    sb.append("    units: ").append(toIndentedString(units)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

