image: timbru31/java-node:8-jdk

stages:
  - build

before_script:
  - chmod +x gradlew
  - mkdir -p $HOME/.docker/
  - echo '{"url":"'$CI_REGISTRY'", "username":"'$CI_USER'", "password":"'$CI_JOB_TOKEN'"}' > $HOME/.docker/config.json

build:
  stage: build
  script: ./gradlew clean buildImage
  artifacts:
    paths:
      - administration/build/libs/administration-0.1-SNAPSHOT.jar
      - time-tracking-server/build/libs/time-tracking-server-0.1-SNAPSHOT.jar
      - worker/build/libs/worker-0.1-SNAPSHOT.jar
