server:
  port: 20081

spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    property-naming-strategy: SNAKE_CASE

# docker run --rm -d --publish=7474:7474 --publish=7687:7687 --volume=$HOME/neo4j/data:/data -e NEO4J_AUTH=neo4j/docker neo4j/neo4j-experimental:4.0.0-rc01
org:
  neo4j:
    driver:
      uri: bolt://localhost:7687
      authentication:
        username: neo4j
        password: docker

time-tracker:
  neo4j:
    schema:
      - CREATE CONSTRAINT ON (user:User) ASSERT user.name IS UNIQUE
      - CREATE CONSTRAINT ON (group:Group) ASSERT group.name IS UNIQUE
      - CREATE CONSTRAINT ON (project:Project) ASSERT project.name IS UNIQUE
      - CREATE (admins:Group {name:"admins"})
      - CREATE (administration:Role {name:"ADMINISTRATOR"})
      - MATCH(g:Group {name:"admins"})
        MATCH(r:Role {name:"ADMINISTRATOR"})
        MERGE(g)-[:HAS_ROLE]->(r)

bcrypt:
  strength: 8

oauth2:
  token:
    validity: 60M
  keys:
    # You should override these!
    priv: classpath:example.pem
    pub: classpath:example.pub


debug: true
