server:
  port: 20080

# docker run --rm -d --publish=7474:7474 --publish=7687:7687 --volume=$HOME/neo4j/data:/data -e NEO4J_AUTH=neo4j/docker neo4j
org:
  neo4j:
    driver:
      uri: bolt://localhost:7474
      authentication:
        username: neo
        password: docker