/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ua.timetracker.desktoptracker.api.tracker.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TimeLogImageDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-04-04T23:10:52.785+03:00[Europe/Kiev]")
public class TimeLogImageDto {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_IMAGEURL = "imageurl";
  @SerializedName(SERIALIZED_NAME_IMAGEURL)
  private String imageurl;


  public TimeLogImageDto id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public TimeLogImageDto imageurl(String imageurl) {
    
    this.imageurl = imageurl;
    return this;
  }

   /**
   * Get imageurl
   * @return imageurl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getImageurl() {
    return imageurl;
  }


  public void setImageurl(String imageurl) {
    this.imageurl = imageurl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeLogImageDto timeLogImageDto = (TimeLogImageDto) o;
    return Objects.equals(this.id, timeLogImageDto.id) &&
        Objects.equals(this.imageurl, timeLogImageDto.imageurl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, imageurl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeLogImageDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    imageurl: ").append(toIndentedString(imageurl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

