/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ua.timetracker.desktoptracker.api.tracker.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TimeLogDtoDurationUnits
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-04-02T21:48:51.378203+03:00[Europe/Kiev]")
public class TimeLogDtoDurationUnits {
  public static final String SERIALIZED_NAME_DATE_BASED = "date_based";
  @SerializedName(SERIALIZED_NAME_DATE_BASED)
  private Boolean dateBased;

  public static final String SERIALIZED_NAME_TIME_BASED = "time_based";
  @SerializedName(SERIALIZED_NAME_TIME_BASED)
  private Boolean timeBased;

  public static final String SERIALIZED_NAME_DURATION_ESTIMATED = "duration_estimated";
  @SerializedName(SERIALIZED_NAME_DURATION_ESTIMATED)
  private Boolean durationEstimated;


  public TimeLogDtoDurationUnits dateBased(Boolean dateBased) {
    
    this.dateBased = dateBased;
    return this;
  }

   /**
   * Get dateBased
   * @return dateBased
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getDateBased() {
    return dateBased;
  }


  public void setDateBased(Boolean dateBased) {
    this.dateBased = dateBased;
  }


  public TimeLogDtoDurationUnits timeBased(Boolean timeBased) {
    
    this.timeBased = timeBased;
    return this;
  }

   /**
   * Get timeBased
   * @return timeBased
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getTimeBased() {
    return timeBased;
  }


  public void setTimeBased(Boolean timeBased) {
    this.timeBased = timeBased;
  }


  public TimeLogDtoDurationUnits durationEstimated(Boolean durationEstimated) {
    
    this.durationEstimated = durationEstimated;
    return this;
  }

   /**
   * Get durationEstimated
   * @return durationEstimated
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getDurationEstimated() {
    return durationEstimated;
  }


  public void setDurationEstimated(Boolean durationEstimated) {
    this.durationEstimated = durationEstimated;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeLogDtoDurationUnits timeLogDtoDurationUnits = (TimeLogDtoDurationUnits) o;
    return Objects.equals(this.dateBased, timeLogDtoDurationUnits.dateBased) &&
        Objects.equals(this.timeBased, timeLogDtoDurationUnits.timeBased) &&
        Objects.equals(this.durationEstimated, timeLogDtoDurationUnits.durationEstimated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dateBased, timeBased, durationEstimated);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeLogDtoDurationUnits {\n");
    sb.append("    dateBased: ").append(toIndentedString(dateBased)).append("\n");
    sb.append("    timeBased: ").append(toIndentedString(timeBased)).append("\n");
    sb.append("    durationEstimated: ").append(toIndentedString(durationEstimated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

